### ISSUE TITLE
Click on Element question

### ISSUE THREAD

**Issue by jenniferamie** [merlinthemagic/MTS#10]
`<a href="javascript:void(0);" class="bblcheck_button" record_id="6227260" rel="prettyPhoto[iframe]" id="check_bl" infovalue="Check">Check</a>
`
I want to click on id="check_bl", but there are so many record_id=[id number]. Can I click to all record_id??

**Comment by merlinthemagic** [comment]
Your question is if you can use a single selector to click multiple elements? The answer is no. The clickElement() method will click the first element selected and then return. 

I am not 100% understanding the objective, are you trying to get images from a website and the images require a button to be clicked before they render on the page? If the images render in the same location ("prettyPhoto[iframe]") you will need to click link, download image, click next link etc. 

As i said i dont fully understand what you are trying to do. Nevertheless here are two ways to click more than one link.

In both solutions you start with a $windowObj and a selector:

```
$url                = "http://www.example.com";
$windowObj      = \MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow($url);

//this selector gets all links that have class "bblcheck_button" specified.
$selector           = "a.bblcheck_button";
```

That was the general part. Next up the solution in PHP per link:

```
//load a custom function onto the page:
$scriptData = "function getLinks() {            
    var rData       = [];
    var eles        = document.querySelectorAll('" . $selector . "');
    if (eles.length > 0) {
        for (var x=0; x < eles.length; x++) {
            var eAttr   = eles[x].getAttribute('record_id');
            if (eAttr != '') {
                rData.push(eAttr);
            }
        }
    }               
    return JSON.stringify(rData);
}";
$windowObj->loadJS($scriptData);

//Call the function and get the record ids back, then click on each link:
$linkArr    = $windowObj->callJSFunction("getLinks");
if ($linkArr != "") {
    $recordIds      = json_decode($linkArr, true);
    foreach ($recordIds as $recordId) {
        $linkSelector   = "[record_id='".$recordId."']";
        $windowObj->clickElement($linkSelector);
    }
}
```

Second Solution all JavaScript:

```
//load a custom function onto the page:
$scriptData = "function clickLinks() {
    var eles        = document.querySelectorAll('" . $selector . "');
    if (eles.length > 0) {
        for (var x=0; x < eles.length; x++) {
            eles[x].click();
        }
    }
    return 'clicked: ' + eles.length + ' links';
}";
$windowObj->loadJS($scriptData);

//Call the function which will click each link:
$clickCount = $windowObj->callJSFunction("clickLinks");
```

You should read up on how to craft CSS selectors.

**Comment by jenniferamie** [comment]
thank you so much !
