### ISSUE TITLE
Install on localhost (windows)

### ISSUE THREAD

**Issue by hasuperus** [merlinthemagic/MTS#11]
I'm using Appserv and got an error when run mtsSetup.php:

`Fatal error: Class 'MTS\Factories' not found in C:\AppServ\www\MTS\MTS\EnableMTS.php on line 34`

What's problem?

**Comment by merlinthemagic** [comment]
There are two issues. 

There is a bug when the MTS folder is inside another folder called MTS. Put it in another folder name I.e. AppServ\www\MtsTool\MTS.......

The second issue is more unfortunate for you, the package is not build for Windows, it relies on Bash currently. I am working on Windows support with Powershell / phantomJS.

**Comment by merlinthemagic** [comment]
I just published the first version that supports Powershell, phantomJS support coming, but not ready yet. If you wanted to use the shell on windows, you now can but it is still rather experimental.

The path bug has also been resolved.

**Comment by merlinthemagic** [comment]
And then PhantomJS for windows was added. Please download the latest version and you will have support for powershell and phantomJS under windows.

**Comment by merlinthemagic** [comment]
@hasuperus can i go ahead and close this issue?
