### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by jenniferamie** [merlinthemagic/MTS#13]
Hello, What is the problem when I run setup

`Fatal error: Uncaught exception 'Exception' with message 'MTS\Common\Devices\Actions\Local\Host\OperatingSystem::execute>> Not Handled for Request Type: getOsObj' in /var/www/html/vc/vc/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php:143 Stack trace: #0 /var/www/html/vc/vc/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php(11): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->execute() #1 /var/www/html/vc/vc/MTS/EnableMTS.php(39): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->getOsObj() #2 /var/www/html/vc/vc/MTS/EnableMTS.php(34): mtsEnvironmentalSetup() #3 /var/www/html/vc/vc/MtsSetup.php(80): require_once('/var/www/html/v...') #4 {main} thrown in /var/www/html/vc/vc/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php on line 143`

Thank you!!

**Comment by merlinthemagic** [comment]
Hi,

What operating system and architecture are you running?

**Comment by garrablanka** [comment]
hello merlinthemagic.
i have the same problem.. i use Centos 6.7 x86_64.
do you know how to fix it?
thanks!

**Comment by merlinthemagic** [comment]
Hi,

Please post the output of $data1 and $data2 to this thread.
$data1 = php_uname();
$data2 = exec("cat /etc/os-release");

MM

**Comment by garrablanka** [comment]
$data1= Linux st.mitrato.cl 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64

$data2= (empty)

**Comment by garrablanka** [comment]
$data2= CentOS release 6.8 (Final)

**Comment by merlinthemagic** [comment]
That was quick ;)

The problem is that we are not getting file return for some reason.

Please test:

$exists = function_exists("exec"); // true or false?
exec("cat /etc/os-release", $data2, $statusArr); // content of $statusArr
Last, does the /etc/os-release file exist?

**Comment by garrablanka** [comment]
$exists is true.
/etc/os-release does not exist but i think you need /etc/centos-release --> CentOS release 6.8 (Final)

**Comment by merlinthemagic** [comment]
Could you post the entire output of /etc/centos-release. 

I will update the OS object to check for that file as well and push a commit tonight.

**Comment by garrablanka** [comment]
only this --> CentOS release 6.8 (Final)
it's an excellent project so I wait for that.
Thanks!

**Comment by garrablanka** [comment]
can you please notify me when you do that??
thanks!!

**Comment by merlinthemagic** [comment]
@garrablanka download the master branch and try again.

**Comment by garrablanka** [comment]
@merlinthemagic 
i downloaded again but i had the same error:
Fatal error: Uncaught exception 'Exception' with message 'MTS\Common\Devices\Actions\Local\Host\OperatingSystem::execute>> Not Handled for Request Type: getOsObj' in /home/lompros/public_html/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php:149 Stack trace: #0 /home/lompros/public_html/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php(11): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->execute() #1 /home/lompros/public_html/merlinthemagic/mts/MTS/EnableMTS.php(39): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->getOsObj() #2 /home/lompros/public_html/merlinthemagic/mts/MTS/EnableMTS.php(34): mtsEnvironmentalSetup() #3 /home/lompros/public_html/MtsSetup.php(80): require_once('/home/lompros/p...') #4 {main} thrown in /home/lompros/public_html/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php on line 149

:(

**Comment by merlinthemagic** [comment]
Odd. 

I would want access to the system to check myself, but that gets complicated. I commited a more verbose version of the OS obj class. Either download the master branch again or just download and override this file: 
https://github.com/merlinthemagic/MTS/blob/master/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php

Are you on IRC somewhere?

**Comment by garrablanka** [comment]
This project looks awesome. So i will give you some access. Give me your email.

**Comment by merlinthemagic** [comment]
Martins@martinpetermadsen.com

**Comment by merlinthemagic** [comment]
Hi,

The install in '/home/lompros/public_html/merlinthemagic/mts' had not been updated to the latest master. But there was other issues as well. 

Thank you for the access. I updated MTS and completed the setup, you are good to go!

MM

**Comment by merlinthemagic** [comment]
@garrablanka Just realized I did not clean up after myself. There is a MtsSetup.php in your root HTML folder. Make sure to get rid of it (I would purge the server completely and spin up another instance. Afterall you don't know me ;))

I also gathered you are using composer,if you download again you need to accept dev packages and specify the master branch (not a release), or just downloa a zip from github.

**Comment by garrablanka** [comment]
thanks very much!!
