### ISSUE TITLE
select option and javascript

### ISSUE THREAD

**Issue by garrablanka** [merlinthemagic/MTS#14]
First of all, i would like to congratule you for this amazing project.

Second, i have a form like this:

`<form name="formit"><select name="juite" onchange="changethis(this.value)"><option value="00" selected>Select option</option><option value="Option*01">Option 1</option><option value="Option*02">Option 2</option><option value="Option*03">Option 3</option><option value="Option*04">Option 4</option><option value="Option*05">Option 5</option></select><a href="javascript:Send('formoptionsnews');"><img src="images/sendform.png"></a></form>`

How can i choose an option and finally send the form??

i tried this to choose an option:
    $windowObj->mouseEventOnElement("[name=juite]", 'leftclick');
    $windowObj->mouseEventOnElement("[value=Option*04]", 'leftclick');
but it doesnt work..

Thanks

**Comment by merlinthemagic** [comment]
Please use the code tag to enclose the form HTML.

**Comment by garrablanka** [comment]
sorry, now you can see it

**Comment by merlinthemagic** [comment]
You are not the first to ask a question like that. It seems i need to write a Wiki. In any case, here is how you can make a selection in the drop down. I will let it be up to you to craft the right css selector to submit the form (I would use the clickElement() method with your CSS selector).

```
//set your variables
$yourUrl	= "http://www.example.com/someForm";
$funcName	= "selectOne";
$formName	= "formit";
$ddName		= "juite";
$ddOptVal	= "Option*04";

//execute
$localHostObj		= \MTS\Factories::getDevices()->getLocalHost();
$windowObj		= $localHostObj->getBrowser('phantomjs')->getNewWindow($yourUrl);

$scriptData = "function ".$funcName."() {
	//get the form element
	var formEle = document.forms['".$formName."'];
	if (typeof formEle != 'object') {
		return 'Form with name: \'".$formName."\', does not exist';
	}
			
	//find the child dropdown element
	var ddEle	= formEle.elements['".$ddName."'];
	if (typeof ddEle != 'object') {
		return 'Dropdown with name \'".$ddName."\' in form: \'".$formName."\', does not exist';
	}
			
	//select the option you want
	ddEle.querySelector(\"option[value='".$ddOptVal."']\").selected = true;
			
	//did we succeed?
	if (ddEle.value == '".$ddOptVal."') {
		return 'Success';
	} else {
		return 'Failure';
	}
}";

//load your script
$windowObj->loadJS($scriptData);
//execute the script
$funcReturn = $windowObj->callJSFunction($funcName);

//render a screenshot to show the dropdown has the desired value. In reallity you will check that 
//$funcReturn == "Success", but for testing an image is more convincing.
echo '<img src="data:image/png;base64,' . base64_encode($windowObj->screenshot()) . '" />';
```

Thats it. Obviously you can remove all the validations if you are certain the element names are valid.

MM

**Comment by garrablanka** [comment]
heey.. this works perfectly! 
thaaanks!!

**Comment by itsmemattchung** [comment]
Thanks @merlinthemagic
