### ISSUE TITLE
simple issue 

### ISSUE THREAD

**Issue by Sarfroz** [merlinthemagic/MTS#15]
hi sir thanks for providing such nice code, i have a simple problem that what to do if phantomjs has been blocked by the website. Any way to fix this kind of problem.

**Comment by itsmemattchung** [comment]
> phantomjs has been blocked by the website

That's interesting—can you elaborate? Can you provide some example output that proves whatever website is actually blocking phantomjs?

**Comment by merlinthemagic** [comment]
Hi @Sarfroz ,

If you are confident the website blocks only phantomJS then it is likely the filtering is done based on the User Agent.

Try this:

```
$url			= "http://www.example.com";

//get a window without setting the URL
$windowObj		= \MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow();

//change the user agent
$agentName	= "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0";
$windowObj->setUserAgent($agentName);

//now set the url
$windowObj->setURL($url);

//then execute your logic... i.e. get DOM
$domData	= $windowObj->getDom();
```

This informs the webserver that firefox, not the default phonatomJS agent is running on the client.

**Comment by Sarfroz** [comment]
try this link with pahntomjs
https://openload.co/f/AvIhwhZwdHY/Moviedetector.Co__lgnh7.mkv

and get element value of <span id="streamurl"> you will get an encoded
value.

**Comment by merlinthemagic** [comment]
Hi @Sarfroz,

The encoded data could only be retrieved from innerHTML. I have added the return from that function to the getElement() method. Download the master and try again.

**Comment by Sarfroz** [comment]
i have found the solution for this too sir but idk how to implement this
with your PHP, because  url will keep changing
i am sending the sample code. if possible try to help this in php form with
your code,

var page = require('webpage').create();
console.log('The default user agent is ' + page.settings.userAgent);
//page.settings.userAgent = 'SpecialAgent';
page.onInitialized = function() {   //this line need to hide phantomjs
  page.evaluate(function() {
    delete window._phantom;
    delete window.callPhantom;
  });
};
page.open('https://openload.co/f/AvIhwhZwdHY/', function(status) { // here
url need to change as per get/post method
  if (status !== 'success') {
    console.log('Unable to access network');
  } else {
    var ua = page.evaluate(function() {
      return document.getElementById('streamurl').textContent;
    });
    console.log(ua);
  }
  phantom.exit();
});

**Comment by merlinthemagic** [comment]
Sry I do not understand the issue.

Are you not able to retrieve the text value of the SPAN? That should be fixed by the current master.
Or are you not able to translate the return value into a URL you can access outside the phantomJS session?

The reason for the second option is this line from JS on the page:

`$('#realdl a').attr("href","/stream/" + $("#streamurl").text());`

It appears they are using an unknown base for encoding the streaming URL.

**Comment by merlinthemagic** [comment]
Try this:

```
$url		= "https://openload.co/f/AvIhwhZwdHY/Moviedetector.Co__lgnh7.mkv";
$windowObj	= \MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow($url);
$domData	= $windowObj->getDom();
		
preg_match("/\/f\/(.*)\//", $url, $urlHash);
preg_match("/var suburl = \"https:\\\\\/\\\\\/thumb.openload.co\\\\\/externsub\\\\\/(.*?)~\";/", $domData, $streamURL);

$link		= $urlHash[1] . "~" . $streamURL[1];
echo $link;
```

**Comment by Sarfroz** [comment]
let me try and tell you :)

**Comment by Sarfroz** [comment]
not working  sir.

**Comment by merlinthemagic** [comment]
@Sarfroz 

You will have to supply more information for me to help you. What exactly are you trying to do? What have you tried? What part of MTS you believe has a bug/needs a feature.

MM
