### ISSUE TITLE
Set cookie again 

### ISSUE THREAD

**Issue by yakupk** [merlinthemagic/MTS#17]
Hi Sir. 
How can I , save cookies of a page I login to and then set **that cookie again** and use it again?
Actually how can I set cookie before request url ? 
Thank You

**Comment by merlinthemagic** [comment]
HI,

Currently not possible but easy to add:

http://phantomjs.org/api/webpage/method/add-cookie.html

I am currently making some long overdue structual changes and ill include this as a feature.

MM

**Comment by yakupk** [comment]
Hi 
Thanks for your reply. I just need to as a feature setCookie method in  'MTS'  library.
