### ISSUE TITLE
How to setCookies for Windows Object

### ISSUE THREAD

**Issue by quyeticb** [merlinthemagic/MTS#18]
have a function: getCookies()
How to set cookies from serialize cookies from getCookies() for after session.

**Comment by merlinthemagic** [comment]
Added this functionallity in the last commit to dev-master. Check updated documentation for the browser under the new method: setCookie()

Please note PhantomJS::addCookie has active issues that are unlikely to be resolved. 

https://github.com/ariya/phantomjs/issues/13409
https://github.com/ariya/phantomjs/issues/14047

#17

**Comment by quyeticb** [comment]
I see, great tool, thanks for fast reply!
