### ISSUE TITLE
WorkDirectory File time extend

### ISSUE THREAD

**Issue by ShayanArifButt** [merlinthemagic/MTS#25]
sometimes when i save a window object;
`
$saveWindowObj = serialize($windowObj);			
$_SESSION['window_obj'] = $saveWindowObj;`

and refresh to try to unserialize and use windowobject ,  after some time , error comes ,

"PHP Fatal error:  Uncaught exception 'Exception' with message 'File does not exist: /home/fankeyco/public_html/1chinadirect/testing/mts_library/MTS/MTS/WorkDirectory/LHB_59b118a98e0ec/stdOut' in /home/fankeyco/public_html/1chinadirect/testing/mts_library/MTS/MTS/Common/Tools/FileSystems/Files.php:29 "

so in the "WorkDirectory" some folders are automatically deleted after few seconds ,  how can we extend the time ? so that they are not deleted quickly and hence i will be able to use the window object, which i saved in a session, for extended time period

**Comment by merlinthemagic** [comment]
The "max_execution_time" that exists at the time the browser is initialized dictates the absolute longest the session is allowed to run. Once it expires the pipes are deleted.

$time = 600; 
ini_set('max_execution_time', $time);
