### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by ShayanArifButt** [merlinthemagic/MTS#27]
So sometimes i get timeout PHP Fatal error when script keeps running for few seconds ( maybe due to slow internet sometimes i guess ) and then stops halfway with timeout error , even though i have set at top of script this ;

`ini_set('max_execution_time', 900);`  ( 15 minutes --> 900 secs )

this is the error:

[17-Sep-2017 04:35:42 America/Denver] PHP Fatal error:  Uncaught exception 'Exception' with message 'MTS\Common\Devices\Browsers\PhantomJS::getSelectorExists>> Got result code: 0, EMsg: timeout, ECode: 408' in /home/fankeyco/public_html/1chinadirect/testing/mts_library/MTS/MTS/Common/Devices/Browsers/PhantomJS.php:227
Stack trace:
#0 /home/fankeyco/public_html/1chinadirect/testing/mts_library/MTS/MTS/Common/Devices/Browsers/Window.php(150): MTS\Common\Devices\Browsers\PhantomJS->getSelectorExists(Object(MTS\Common\Devices\Browsers\Window), '[name=code]')
#1 /home/fankeyco/public_html/1chinadirect/testing/mts_library/mts_amazon_add_address.php(610): MTS\Common\Devices\Browsers\Window->getSelectorExists('[name=code]')
#2 {main}
  thrown in /home/fankeyco/public_html/1chinadirect/testing/mts_library/MTS/MTS/Common/Devices/Browsers/PhantomJS.php on line 227

**Comment by merlinthemagic** [comment]
Besides the overall scrip time there is also a per command timeout. By default it is set to 30000ms, but you can change it by running:


//on the BROWSER OBJ!
$browserObj->setDefaultExecutionTime($milliSecs);

**Comment by Casantana** [comment]
thank you. really helpful
