### ISSUE TITLE
Could not determine OS distribution

### ISSUE THREAD

**Issue by rosariogueli** [merlinthemagic/MTS#35]
When launching the MtsSetup.php file in my website's public folder, when I set the correct path to the MTS library and click setup, I get the error at the end of this post. I'm running this on my LAMP setup on Amazon Linux AMI release 2016.09, here more info about my setup: 

cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2016.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.09"
PRETTY_NAME="Amazon Linux AMI 2016.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

And here the error I get: 

Fatal error: Uncaught exception 'Exception' with message 'MTS\Common\Devices\Actions\Local\Host\OperatingSystem::execute>> Could not determine OS distribution' in /var/www/library/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php:115 Stack trace: #0 /var/www/library/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php(11): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->execute() #1 /var/www/library/MTS/EnableMTS.php(39): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->getOsObj() #2 /var/www/library/MTS/EnableMTS.php(34): mtsEnvironmentalSetup() #3 /var/www/thegroomersspotlight/public/MtsSetup.php(80): require_once('/var/www/librar...') #4 {main} thrown in /var/www/library/MTS/Common/Devices/Actions/Local/Host/OperatingSystem.php on line 115

**Comment by merlinthemagic** [comment]
Hi,

Added identification abbreviation "rhel" for RedHat based distros to master. Pl;ease clone master and try again.

MM

**Comment by rosariogueli** [comment]
Hi, this worked perfectly. Thank you so much!
