### ISSUE TITLE
How to install MTS manually without PHP automation install (MtsSetup.php) ?

### ISSUE THREAD

**Issue by plonknimbuzz** [merlinthemagic/MTS#36]
hi bro,
after several weeks i use MTS, i use in my VPS ubuntu which is working awesome.

2 days ago, i try to install it in my laptop 
1. windows 7 SP1 32 bit (localhost)
2. PHP 7.1 (XAMPP)
3. python 3.6.3
4. Powershell 6.0.0-rc-win-x86
5. cygwin 2.9.0 (python 2.7)
6. win 7 SP1 cmd

i try both browser and CLI (cmd, ps, cygwin) installation but i got error. I fix the MTS source but still didnt get right.

if i read the doc carefully, this issue https://github.com/merlinthemagic/MTS/issues/11 , and the source which have inconsistance $OsName for Windows (some script use `Windows`, some use `windows`. and some of them use comparison $OsName without case insensitive (strtolower). i get that MTS was not fully already for windows. CMIIW

But, since python, phantomJS which is core for MTS. i think MTS should can run in windows too.

So, now i want to know how to install MTS manually without MtsSetup.php.

1. we skip using `composer require merlinthemagic/MTS` seems no other dependencies from other github there. so we can just download the source (zip) from github.
2. PHP 5.3++ installed and make sure this allowed:
a. exec()
b. popen()
c. pclose()
d. proc_open()
3. python 3.x.x installed
4. phantomJS installed
5. make sure php, python, phantomJS registered in System Path Environment

what's next?

problem:
1. inconsistance in windows OsName: windows and Windows
2. no linux `screen` alternative in windows. i can get this using cygwin but still fail to install MTS. and actually i dont know what screen usage and what screen did in MTS. so i really blank of this
3. we cant use exec("where python") so easly using browser installation in windows. we must give much effort to make this run. really!! i take this part 6 hours 

forgot the rest (so sleepy yesterday).

Note: i hope i can help pull something if i get correct information

**Comment by plonknimbuzz** [comment]
OMG.
i make very very big mistake here.

i miss understood the MTS usage. 
Browser: how to get browser automation using PHP. and MTS using phantomJS to control the browser
Shell: how to control shell using PHP for automation purpose. we can use bash, cmd, powershell

my mistake is never read MTS/SHELL_README.md until the end.
what i thought that MTS is phantomJS library for PHP. we can run MTS using browser or CLI. (OMG).

> What is this?
>
>Simple, its a tool set for PHP. Currently comprised of two core components shell and browser.


that's why in my first issue i try to compare MTS vs PhantomJS, casperJS and SlimmerJS. LOL 
i think you should ignore this issue first. 
i will try all over again.
sorry

**Comment by merlinthemagic** [comment]
HI,

Not 100% sure what you are hinting at, but it seems you expected MTS required a cygwin installation to function. That is not the case, MTS runs on windows natively.

You mention "inconsistance in windows OsName: windows and Windows", what file?

MM

**Comment by plonknimbuzz** [comment]
ofc you will not get what i mean. because its slightly different when i realise what is MTS 

i working on this now. 
- try install in several machine (all windows)
- readme.md , 
- install.md and 
- create example
- inconsistance windows OsName

this will take several days, because my daughter wont allow me to finish this fast. haha
if i'm ready i will send pull request

note: i really know that i get out of topic (my issue title). but in several part i still on the track. i will fix this after several trial. just dont close this issue yet

**Comment by plonknimbuzz** [comment]
merlin can you check this https://github.com/merlinthemagic/MTS/pull/37

btw, can i totally modify Linux installation? because it's really confusing to follow that.
i will create manual installation instead using MtsSetup.php

**Comment by plonknimbuzz** [comment]
btw, i download MTS 2 weeks ago for my ubuntu. And 2 days ago for my windows.

but they have different output
`$windowObj->getElement('title')['innerHTML'];`
my 1st MTS (ubuntu):  `Wikipedia`
my 2nd MTS (windows): `(empty)`

when i copy my MTS on ubuntu to windows. i got correct result `Wikipedia`. So i think you change something in master branch.

i think we should provides `realese` zip file or add new develop branch.
So this will not happen again.

**Comment by merlinthemagic** [comment]
Hi,

Master is going to change over time. If you want consistent results you have to use one of the releases. There is little point in making a new release every time a minor feature is updated.

MM

**Comment by plonknimbuzz** [comment]
thanks. i still watch this repo. usefull for me to feed my fren with pure php code, because they lack of javascript (especilly phantomJS) knowledge
