### ISSUE TITLE
error excecuting command

### ISSUE THREAD

**Issue by equisde** [merlinthemagic/MTS#40]
Hi merlinthemagic,,
before all thanks for this great project!

when i send command with 
$sent  = $shellObj->exeCmd($daemon." sendfrom ".$faucetd." ".$wallet." ".$faucet);
it should get in to a coin daemon and excecute command but it doesnt get $faucet variable that it is 0.08, and when i excecute the code 
i get error from coin daemon saying that i must use the command with sendfrom <fromwallet> <towallet ammount>
as i can see it is not sending the last variable that is 0.08 and it says 0.08: command not found
if i go to shell and excecute that command i'm able to do that directly from coin daemoin 

all vars where given by database i'm able to do 
$sent  = $shellObj->exeCmd($daemon." getbalance ".$wallet);
with no problems

so i think is an issue with MTS that is not sending all vars any help?

**Comment by merlinthemagic** [comment]
Hi,

The MTS shell does not treat the string command as individual arguments. It simply passes the string on to the terminal and hits the enter key.

It seems the sting you send is interpreted as 2 separate commands. That is why you get the "0.08" command not found.

My guess is that your $wallet variable contains a newline (\n) character at the end. That would fit your description. 
Try:

`$sent = $shellObj->exeCmd($daemon." sendfrom ".$faucetd." ".rtrim($wallet)." ".$faucet);`

**Comment by equisde** [comment]
will give it a try thanks for your time!

**Comment by equisde** [comment]
thanks! it works!
thanks a lot for your time
amazing project!
