### ISSUE TITLE
Error when connecting...

### ISSUE THREAD

**Issue by GHNJ** [merlinthemagic/MTS#47]
Hi, my goal is to connect to the first server, then tunnel to a second one, and get the last 300 lines of a log file.

both servers are RHEL and I can use putty to ssh to both w/out issues using username and pw. 

Here is my code: 

` require_once "c:\\xampp\htdocs\\tools\\MTS\\EnableMTS.php";

//first you get a shell on the first server:
$shellObj = \MTS\Factories::getDevices()->getRemoteHost('192.168.1.14')->setConnectionDetail('test', 'test')->getShell('bash', false);

//then build on that first shell, the following way.
\MTS\Factories::getDevices()->getRemoteHost('10.10.10.48')->setConnectionDetail('user', 'test')->getShell($shellObj);

//any command executed on the shell will run only on the second host you connected to.
$return1  = $shellObj->exeCmd("hostname");
echo $return1;//hostname of the second host you connected to`

when I run the above, I get the below error message: 

--------------------------------------------------------------------------------------------------------------------------
( ! )  Fatal error: Uncaught Error: Call to a member function getActiveShell()  on string in  C:\xampp\htdocs\tools\MTS\Common\Devices\Actions\Remote\Connections\Ssh.php  on line 31
--

1 | 0.2088 | 405480 | {main}(  ) | ...\test.php:0
2 | 0.6057 | 506984 | MTS\Common\Devices\Types\Remotehost->getShell(  ) | ...\test.php:24
3 | 0.6073 | 554888 | MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsername(  ) | ...\Remotehost.php:73
4 | 0.6073 | 555264 | MTS\Common\Devices\Actions\Remote\Connections\Ssh->execute(  ) | ...\Ssh.php:18

--------------------------------------------------------------------------------------------------------------------------

**Comment by merlinthemagic** [comment]
ya. Its been awhile since i looked at this, but if you look at the [section you copied ](https://github.com/merlinthemagic/MTS/blob/master/SHELL_README.md#remote-shells-linux-only) is say Linux only in the header.

The reason MTS cannot act as an ssh client is that elevating a power shell to allow ssh ends up spawning a brand new process we cant hook into from cli,.

Anyways, if you still wanna accomplish the task switch to a linux based environment and use the [maintained version of this lib](https://github.com/merlinthemagic/MTM-SSH).

**Comment by GHNJ** [comment]
Thanks for the quick reply! 

So from what I understand, since my dev env is on windows (running xampp), then the MTS script will not work correct? 
I'll have to setup a Linux env and then I can use it?

**Comment by merlinthemagic** [comment]
yes, linux will do the job just fine. Again i urge you to use [mtm-ssh](https://github.com/merlinthemagic/MTM-SSH) rather than MTS. 

The MTM packages are far better performing, no need for screen or custom setup, they work right from the get go and clean up much nicer than MTS

**Comment by GHNJ** [comment]
Thanks for the information and help! Much appreciated.
