### ISSUE TITLE
Class 'MTS\Factories' not found

### ISSUE THREAD

**Issue by enckwab** [merlinthemagic/MTS#50]
I have created a file and added this code <?php 
$myUrl          = "http://www.youtube.com";
$windowObj      = \MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow($myUrl);

//now you can either retrive the DOM and parse it, like this:
$domData    = $windowObj->getDom();

//this project also lets you manipulate the live page. Click, fill forms, submit etc.

?>

When I try to laujnch it, it get this error Class 'MTS\Factories' not found

**Comment by merlinthemagic** [comment]
You have to include the auto loader before you can access the factory:

require_once "c:\path\to\mts\folder\EnableMTS.php";

https://github.com/merlinthemagic/MTS/blob/master/INSTALL.md
