### ISSUE TITLE
Fatal error: Uncaught Exception Could not determine OS version

### ISSUE THREAD

**Issue by AugustineSena** [merlinthemagic/MTS#52]
I Caught the error while after run `composer dump-autoload`. I am running on Windows NT Desktop 6.0 build 6002 (Windows Server 2008 Enterprise Edition Service Pack 2) (I am aware of my server outdated :'( ). Please I need help, what am I supposed to do then ? Thanks in advance.

`Fatal error: Uncaught Exception: MTS\Common\Devices\Actions\Local\Host\OperatingSystem::execute>> Could not determine OS version in C:\xampp\htdocs\myproject\vendor\merlinthemagic\mts\MTS\Common\Devices\Actions\Local\Host\OperatingSystem.php:117 Stack trace: #0 C:\xampp\htdocs\myproject\vendor\merlinthemagic\mts\MTS\Common\Devices\Actions\Local\Host\OperatingSystem.php(11): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->execute() #1 C:\xampp\htdocs\myproject\vendor\merlinthemagic\mts\MTS\EnableMTS.php(39): MTS\Common\Devices\Actions\Local\Host\OperatingSystem->getOsObj() #2 C:\xampp\htdocs\myproject\vendor\merlinthemagic\mts\MTS\EnableMTS.php(34): mtsEnvironmentalSetup() #3 C:\xampp\htdocs\myproject\vendor\composer\autoload_real.php(69): require('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\myproject\vendor\composer\autoload_real.php(59): composerRequire981082f7a0b8008583433cb793079xxx('028ab563f39ac1e...', 'C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\myproject\vendor\autoload.php(7): ComposerAutoloaderInit981082f7a0b80085xxx in C:\xampp\htdocs\myproject\vendor\merlinthemagic\mts\MTS\Common\Devices\Actions\Local\Host\OperatingSystem.php on line 117`

**Comment by merlinthemagic** [comment]
Hi @AugustineSena ,

I dont have that specific version of windows server running anywhere so ill need you to give me the output of these two commands run on a standard command line (CMD):

```
wmic OS get Name
wmic OS get OSArchitecture
```

You should get something like this (example using 2008R2):

```
C:\>wmic OS get Name
Name
Microsoft Windows Server 2008 R2 Standard |C:\Windows|\Device\Harddisk0\Partition2


C:\>wmic OS get OSArchitecture
OSArchitecture
64-bit
```

**Comment by AugustineSena** [comment]
Here it is
```
C:\>wmic OS get name
Name                                                                            
Microsoftr Windows Serverr 2008 Enterprise |C:\Windows|\Device\Harddisk0\Partition1
```

```
C:\>wmic OS get OSArchitecture
OSArchitecture
32-bit
```

**Comment by merlinthemagic** [comment]
Hi,

I see, its a couple of registered trademark (®) symbols that's not translating correctly.

I added logic to strip out the extra chars, download master and try again.

**Comment by AugustineSena** [comment]
Well, Thanks a lot it works
