### ISSUE TITLE
How to set user agent?

### ISSUE THREAD

**Issue by hnhhl** [merlinthemagic/MTS#6]
Hello, thank you for perfect source !
I'm new for PHP. I don't know how to set user agent in your code.
My code:
<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);
require_once "/var/www/html/master/MTS/EnableMTS.php";
ini_set('max_execution_time', 120);
$myUrl          = "https://whoer.net";
$agentName  = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0";
$windowObj->setUserAgent($agentName);
$windowObj      = \MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow($myUrl);
?>

And I got error:

Notice: Undefined variable: windowObj in /var/www/html/master/test2.php on line 9

Fatal error: Uncaught Error: Call to a member function setUserAgent() on null in /var/www/html/master/test2.php:9 Stack trace: #0 {main} thrown in /var/www/html/master/test2.php on line 9

Please give me an idea. Thank you so much ~!

**Comment by merlinthemagic** [comment]
Almost right :). But you need to instantiate the browser, then get a window object before you start calling methods on it. Here is a working example:

```
error_reporting(E_ALL);
ini_set("display_errors", 1);
ini_set('max_execution_time', 120);

require_once "/var/www/html/master/MTS/EnableMTS.php";

$myUrl = "https://whoer.net";
$windowObj = MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow($myUrl);


$agentName = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0";
$windowObj->setUserAgent($agentName);
```

Now you can start calling other methods on the windowObj. I.e. if you want a screenshot of the page you have open in the window:

```
//take screenshot
$screenshotData = $windowObj->screenshot();
//render it:
echo '<img src="data:image/png;base64,' . base64_encode($screenshotData) . '" />';
```

**Comment by hnhhl** [comment]
Thank you for quick reply. I edited code :+1: 

<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);
ini_set('max_execution_time', 120);
require_once "/var/www/html/master/MTS/EnableMTS.php";
$myUrl = "https://whoer.net";
$windowObj = MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow($myUrl);
$agentName = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0";

$windowObj->setUserAgent($agentName);
$screenshotData = $windowObj->screenshot();
echo '<img src="data:image/png;base64,' . base64_encode($screenshotData) . '" />';

$domData    = $windowObj->getDom();
echo $domData;

?>

Now I got the screenshot taken from whoer.net (website to check current user agent) , but the user agent on that screenshot and from domData is  "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"

It's not working for me... :(

**Comment by merlinthemagic** [comment]
Got it. The reason is that setting the url when instantiating a new window will call setURL() before the agent is changed. I should have realized you wanted the agent reflected on the initial connection.
Here is a corrected example:

```
error_reporting(E_ALL);
ini_set("display_errors", 1);
ini_set('max_execution_time', 120);

require_once "/var/www/html/master/MTS/EnableMTS.php";

//do not set URL while instantiating
$windowObj = MTS\Factories::getDevices()->getLocalHost()->getBrowser('phantomjs')->getNewWindow();

//set agent
$agentName = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0";
$windowObj->setUserAgent($agentName);

//now set url
$myUrl = "https://whoer.net";
$windowObj->setURL($myUrl);

//window now executes requests with correct agent
$screenshotData = $windowObj->screenshot();
echo '<img src="data:image/png;base64,' . base64_encode($screenshotData) . '" />';
```

**Comment by hnhhl** [comment]
Thank you for answer. My problems is now resolved !!!
This is the best source I've ever known.
The last question, can I set time zone and use proxy to connect to $myurl ?

**Comment by merlinthemagic** [comment]
Currently not possible using MTS. You would have to modify the options when phantomJS is started.

See: [documentation](http://phantomjs.org/api/command-line.html)
Specifically the options:

```
--proxy=address:port
--proxy-type=[http|socks5|none]
```

Append the command on line 45 of [Browser.php](https://github.com/merlinthemagic/MTS/blob/master/MTS/Common/Devices/Actions/Local/Host/Browser.php)

With the proxy settings. I will consider implementing it as a feature later.
