### ISSUE TITLE
how to use mysql in code?

### ISSUE THREAD

**Issue by hnhhl** [merlinthemagic/MTS#7]
Hi, I inserted mysql connect in the top of page after <?php to use database :

```
define('db_host','localhost');
define('db_data','database');
define('db_user','root');
define('db_pass','password');
mysql_connect(db_host,db_user,db_pass) or die("Not the connect to database");
mysql_select_db(db_data) or die ("Not found database");
```

And error:

`Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/master/test.php:6 Stack trace: #0 {main} thrown in /var/www/html/master/test.php on line 6`

Please help me. Thank you very much

**Comment by merlinthemagic** [comment]
You must be new to the open source community or programming in general.
This place is only for issues regarding MTS and your question has nothing to do with the MTS package.

I would normally suggest you ask your question on i.e. stack exchange or a similar forum, but in this case the question has been answered literally 100s of times before. You need to make an effort to learn the basics on your own using the vast resources of the internet.

I am happy to answer questions regarding MTS and its use, but i am not your general goto source for PHP learning.

**Comment by hnhhl** [comment]
Hi,  yes I'm using MTS code and want to use database in it. But when i use database its error:

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/master/test.php:6 Stack trace: #0 {main} thrown in /var/www/html/master/test.php on line 6

**Comment by itsmemattchung** [comment]
> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/master/test.php:6 Stack trace: #0 {main} thrown in /var/www/html/master/test.php on line 6

hey @hnhhl , it appears that `mysql_connect` is deprecated, according to [this post](http://stackoverflow.com/questions/15346605/php-apache-php-fatal-error-call-to-undefined-function-mysql-connect) on stackoverflow; the second comment suggests installing the dependencies—php5 mysql—via your package manager.  Can you try that and see if that works?
