### ISSUE TITLE
Bash not available on localHost

### ISSUE THREAD

**Issue by Nguy3nM1nhVu0ng** [merlinthemagic/MTS#8]
I get an error !
Fatal error: Uncaught exception 'Exception' with message 'MTS\Common\Devices\Actions\Local\Host\Shell::execute>> Bash not available on localHost

**Comment by merlinthemagic** [comment]
Please provide your OS distribution, version and architecture. And a snip of code you are trying to execute when you get the error.

**Comment by Nguy3nM1nhVu0ng** [comment]
OS                : CentOS
Version         : 7.4
Architecture : 64bit

Mycode:

<pre>
$shellObj    = \MTS\Factories::getDevices()->getLocalHost()->getShell('bash', false);
$shellObj->exeCmd('cd /var/log/');
$return1  = $shellObj->exeCmd('ls -sho --color=none');
echo $return1;
</pre>

**Comment by merlinthemagic** [comment]
Please execute these 3 commands from PHP using the SAME user as you did for the MTS command:

```
$who = exec("whoami");
$paths = exec("echo \$PATH");
$bashExePath = exec("which bash");
```

then post the return from each of the 3 commands.

**Comment by Nguy3nM1nhVu0ng** [comment]
I was running and this is the result

<pre>
string(4) "root"
string(148) "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin"
string(13) "/usr/bin/bash"
</pre>

**Comment by merlinthemagic** [comment]
Are you sure the all commands where issued as root?

The reason I ask is that the last command you executed (which bash) is the command that would need to fail for you to get the original exception. but it returns the path to the bash executable just like it should.

Something in your environment MUST have changed since you got the exception. For example did you execute the MTS shell via a browser and the "exec("which bash")" in CLI?

Try executing the original shell commands again.

**Comment by Nguy3nM1nhVu0ng** [comment]
@merlinthemagic  Yep you're right.
I have run it in the browser and the results below.

<pre>
string(5) "nginx"
string(23) "/usr/local/bin:/usr/bin"
string(0) ""
</pre>

And i was run in cli

<pre>
Interactive shell
php > echo exec("which bash");
/usr/bin/bash
php >
</pre>

**Comment by merlinthemagic** [comment]
Thanks, that makes more sense :).

Is your system enforcing SE? 
To make sure please issue the following command: "sestatus" on the command line and post the results here.

If you do not have shell access you could try through the webserver like this:

```
exec("sestatus", $return);
echo "<pre>" . implode("\n", $return) . "</pre>";
```

The next part is NOT a solution, it is simply troubleshooting. 

If you see the folllowing in the "sestatus" return:

`Current mode:                   enforcing`

Then try issuing the following command on the command line: "setenforce 0".
This will temporarily change the SE from enforcing to permissive (warning vs denied).

Then run the "exec("which bash")" from the webserver again.

**Comment by Nguy3nM1nhVu0ng** [comment]
Thank you for your great support.
I was run your code and returned empty !
So I run command "sestatus" in terminal and this resulting is:

<pre>[root@***]# sestatus
SELinux status:                 disabled
</pre>

I was setup centminmod on my server. Do you have any solution to my problem. Any ideas?

**Comment by merlinthemagic** [comment]
Hi,

I think the issue comes about because NGINX does not manage the environmental variables like apache would. Try adding this line in your PHP script before anything else:

`putenv("PATH=" . exec("echo \$PATH"));`

Then run the MTS commands.

**Comment by Nguy3nM1nhVu0ng** [comment]
@merlinthemagic 
great, it worked ! thank you  very much.

**Comment by merlinthemagic** [comment]
Download the latest from the master branch, the fix has been added to the default setup.
