### ISSUE TITLE
Save all cookie to txt file

### ISSUE THREAD

**Issue by jenniferamie** [merlinthemagic/MTS#9]
Hello, how to save all cookie to a txt file and then read cookie from this? thank you

**Comment by merlinthemagic** [comment]
The getCookies() method returns an array. You would have to decide on a file format to accommodate the structure of the array. Alternatively you could serialize the array and simply save that in a file i.e:

```
//save array
$cookieArray = $windowObj->getCookies();
file_put_contents('/tmp/filename.ser', serialize($cookieArray));
```

Then when you need the cookies again:

```
//read array
$cookieArray = unserialize(file_get_contents('/tmp/filename.ser'));
```

**Comment by jenniferamie** [comment]
Thank you for your answer ! 
Another question, can I send a 'Tab' key?

**Comment by merlinthemagic** [comment]
Hi,

I just added the abillity to send "Tab" key press, so you will need to download MTS again (master branch), alternatively you can just override PJSCtrl.js with the newest version [(PJSCtrl.js)](https://github.com/merlinthemagic/MTS/blob/master/MTS/Common/Devices/VendorData/phantomJS/PJSCtrl.js).

I assume you are trying to move the cursor focus to next input using Tab. In that case be aware that tab behavior is programmable and may not yield the result you expect for certain [sites](http://w3c.github.io/html/editing.html#the-tabindex-attribute), default behavior depends on the user agent . Using $windowObj->focusElement($selector); MAY be better approach in some situations where elements are not assigned dynamic attributes.

```
//here is how to send special key "Tab":
$windowObj->sendKeyPresses(array("Tab"));
```

**Comment by merlinthemagic** [comment]
@jenniferamie Where you able to send Tab? Can i close the issue?

**Comment by jenniferamie** [comment]
Hello, thank you so much !!!!
